// Grandes empresas que publican muchas vacantes en portales de empleo
export const EMPRESAS_DESTACADAS = [
  // Distribución y retail
  'Mercadona',
  'El Corte Inglés',
  'Carrefour',
  'Lidl',
  'Aldi',
  'Alcampo',
  'Dia',
  'Eroski',
  'Consum',
  'Leroy Merlin',
  'IKEA',
  'Decathlon',
  'MediaMarkt',
  'Primark',
  'Amazon',
  'Inditex',
  'Zara',
  'Mango',
  'Tendam',
  'Grupo Eroski',
  // Banca y seguros
  'Banco Santander',
  'BBVA',
  'CaixaBank',
  'Banco Sabadell',
  'Bankinter',
  'ING',
  'Mapfre',
  'Mutua Madrileña',
  'Allianz',
  'AXA',
  'Generali',
  'Línea Directa',
  // Telecomunicaciones y tecnología
  'Telefónica',
  'Movistar',
  'Vodafone',
  'Orange',
  'MásMóvil',
  'Cellnex',
  'Ericsson',
  'IBM',
  'Microsoft',
  'Google',
  'Amazon Web Services',
  'SAP',
  'Oracle',
  // Energía y utilities
  'Iberdrola',
  'Endesa',
  'Naturgy',
  'Repsol',
  'Cepsa',
  'Acciona',
  'EDP',
  'Enagás',
  'Redeia (Red Eléctrica)',
  // Construcción e infraestructuras
  'ACS',
  'Ferrovial',
  'Sacyr',
  'FCC',
  'OHLA',
  'Acciona Construcción',
  // Automoción e industria
  'SEAT',
  'CUPRA',
  'Volkswagen Navarra',
  'Renault España',
  'Stellantis',
  'Ford España',
  'Mercedes-Benz España',
  'Iveco',
  'Gestamp',
  'Grupo Antolin',
  'Michelin',
  'Siemens',
  'Siemens Gamesa',
  'Airbus',
  'Navantia',
  // Alimentación y gran consumo
  'Danone',
  'Nestlé España',
  'Coca-Cola Europacific Partners',
  'Mahou San Miguel',
  'Grupo Damm',
  'Calidad Pascual',
  'Campofrío',
  'Ebro Foods',
  'Grupo Dcoop',
  'Capsa Food',
  'Grupo Bimbo',
  // Salud y farma
  'Sanitas',
  'Quirónsalud',
  'HM Hospitales',
  'Vithas',
  'Grifols',
  'Almirall',
  'Laboratorios Rovi',
  'Cinfa',
  'Ferrer',
  'Rovi',
  // Transporte, logística y viajes
  'Correos',
  'SEUR',
  'MRW',
  'DHL',
  'GLS',
  'Renfe',
  'Iberia',
  'Vueling',
  'Air Europa',
  'Amazon Logistics',
  'CTT Express',
  // Hostelería, turismo y restauración
  'Meliá Hotels International',
  'NH Hotel Group',
  'Riu Hotels',
  'Barceló',
  'Iberostar',
  "McDonald's",
  'Burger King',
  'Grupo Vips',
  'Telepizza',
  'Areas',
  'Eurest',
  'Grupo Compass',
  // Seguridad y servicios
  'Prosegur',
  'Securitas',
  'Ilunion',
];

export default EMPRESAS_DESTACADAS;
