export const UBICACIONES_POR_PROVINCIA = [
  {
    provincia: 'A Coruña',
    ciudades: [
      'A Coruña',
      'Santiago de Compostela',
      'Ferrol',
      'Narón',
      'Oleiros',
      'Arteixo',
      'Culleredo',
      'Carballo',
      'Ames',
      'Ribeira',
      'Boiro',
      'Cambre',
      'A Pobra do Caramiñal',
      'Betanzos',
      'Sada',
      'Noia',
      'Padrón',
      'Ordes',
      'Melide',
      'As Pontes de García Rodríguez',
      'Cee',
      'Fene',
      'Cedeira',
      'Teo',
      'Pontedeume',
    ],
  },
  {
    provincia: 'Álava',
    ciudades: ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra', 'Oyón'],
  },
  {
    provincia: 'Albacete',
    ciudades: [
      'Albacete',
      'Hellín',
      'Villarrobledo',
      'Almansa',
      'La Roda',
      'Caudete',
      'Tobarra',
      'Tarazona de la Mancha',
      'Casas-Ibáñez',
    ],
  },
  {
    provincia: 'Alicante',
    ciudades: [
      'Alicante',
      'Elche',
      'Torrevieja',
      'Orihuela',
      'Benidorm',
      'Alcoy',
      'Elda',
      'San Vicente del Raspeig',
      'Dénia',
      'Villena',
      'Petrer',
      'La Vila Joiosa',
      'Santa Pola',
      'Crevillent',
      'Novelda',
      'Ibi',
      'Altea',
      'Calpe',
      'Xàbia',
      'Aspe',
      'Pego',
      'Cocentaina',
      'Mutxamel',
      'El Campello',
      'Guardamar del Segura',
      'Sax',
      'Monóvar',
      'Callosa de Segura',
      'Almoradí',
    ],
  },
  {
    provincia: 'Almería',
    ciudades: [
      'Almería',
      'Roquetas de Mar',
      'El Ejido',
      'Níjar',
      'Adra',
      'Vícar',
      'Huércal de Almería',
      'Berja',
      'Cuevas del Almanzora',
      'Vera',
      'Huércal-Overa',
      'Garrucha',
      'Carboneras',
      'Pulpí',
    ],
  },
  {
    provincia: 'Asturias',
    ciudades: [
      'Oviedo',
      'Gijón',
      'Avilés',
      'Siero',
      'Langreo',
      'Mieres',
      'Castrillón',
      'San Martín del Rey Aurelio',
      'Corvera de Asturias',
      'Villaviciosa',
      'Llanera',
      'Cangas de Onís',
      'Cangas del Narcea',
      'Llanes',
      'Grado',
      'Laviana',
    ],
  },
  {
    provincia: 'Ávila',
    ciudades: [
      'Ávila',
      'Arévalo',
      'Arenas de San Pedro',
      'Las Navas del Marqués',
    ],
  },
  {
    provincia: 'Badajoz',
    ciudades: [
      'Badajoz',
      'Mérida',
      'Don Benito',
      'Almendralejo',
      'Villanueva de la Serena',
      'Zafra',
      'Montijo',
      'Villafranca de los Barros',
      'Olivenza',
      'Jerez de los Caballeros',
      'Azuaga',
    ],
  },
  {
    provincia: 'Baleares',
    ciudades: [
      'Palma',
      'Calvià',
      'Manacor',
      'Ibiza',
      'Santa Eulària des Riu',
      'Llucmajor',
      'Marratxí',
      'Inca',
      'Sant Antoni de Portmany',
      'Alcúdia',
      'Pollença',
      'Felanitx',
      'Sóller',
      'Andratx',
      'Ciutadella de Menorca',
      'Maó',
      'Sant Josep de sa Talaia',
      'Capdepera',
    ],
  },
  {
    provincia: 'Barcelona',
    ciudades: [
      'Barcelona',
      "L'Hospitalet de Llobregat",
      'Badalona',
      'Terrassa',
      'Sabadell',
      'Mataró',
      'Santa Coloma de Gramenet',
      'Cornellà de Llobregat',
      'Sant Cugat del Vallès',
      'Manresa',
      'Rubí',
      'Vilanova i la Geltrú',
      'Viladecans',
      'El Prat de Llobregat',
      'Castelldefels',
      'Granollers',
      'Cerdanyola del Vallès',
      'Mollet del Vallès',
      'Sant Boi de Llobregat',
      'Esplugues de Llobregat',
      'Gavà',
      'Igualada',
      'Vic',
      'Sant Adrià de Besòs',
      'Barberà del Vallès',
      'Montcada i Reixac',
      'Sant Feliu de Llobregat',
      'Ripollet',
      'Premià de Mar',
      'Vilafranca del Penedès',
      'Sant Joan Despí',
      'Martorell',
      'Sant Andreu de la Barca',
      'Sitges',
      'Pineda de Mar',
      'Manlleu',
      'Sant Vicenç dels Horts',
      'Molins de Rei',
      'Calella',
      'Berga',
    ],
  },
  {
    provincia: 'Bizkaia',
    ciudades: [
      'Bilbao',
      'Barakaldo',
      'Getxo',
      'Portugalete',
      'Santurtzi',
      'Basauri',
      'Leioa',
      'Galdakao',
      'Sestao',
      'Durango',
      'Erandio',
      'Abadiño',
      'Amorebieta-Etxano',
      'Mungia',
      'Bermeo',
      'Gernika-Lumo',
      'Ermua',
      'Sopelana',
      'Arrigorriaga',
    ],
  },
  {
    provincia: 'Burgos',
    ciudades: [
      'Burgos',
      'Miranda de Ebro',
      'Aranda de Duero',
      'Briviesca',
      'Medina de Pomar',
      'Villarcayo',
      'Lerma',
    ],
  },
  {
    provincia: 'Cáceres',
    ciudades: [
      'Cáceres',
      'Plasencia',
      'Navalmoral de la Mata',
      'Miajadas',
      'Trujillo',
      'Coria',
      'Moraleja',
      'Jaraíz de la Vera',
    ],
  },
  {
    provincia: 'Cádiz',
    ciudades: [
      'Cádiz',
      'Jerez de la Frontera',
      'Algeciras',
      'San Fernando',
      'El Puerto de Santa María',
      'Chiclana de la Frontera',
      'La Línea de la Concepción',
      'Sanlúcar de Barrameda',
      'Puerto Real',
      'Rota',
      'Arcos de la Frontera',
      'Los Barrios',
      'Barbate',
      'Conil de la Frontera',
      'San Roque',
      'Tarifa',
      'Ubrique',
      'Medina-Sidonia',
      'Vejer de la Frontera',
    ],
  },
  {
    provincia: 'Cantabria',
    ciudades: [
      'Santander',
      'Torrelavega',
      'Castro-Urdiales',
      'Camargo',
      'Piélagos',
      'El Astillero',
      'Santoña',
      'Laredo',
      'Los Corrales de Buelna',
      'Reinosa',
      'Santa María de Cayón',
      'Suances',
    ],
  },
  {
    provincia: 'Castellón',
    ciudades: [
      'Castellón de la Plana',
      'Vila-real',
      'Burriana',
      'Vinaròs',
      'Benicàssim',
      'Almassora',
      "La Vall d'Uixó",
      'Onda',
      'Benicarló',
      'Nules',
      'Segorbe',
      'Oropesa del Mar',
      'Peñíscola',
    ],
  },
  { provincia: 'Ceuta', ciudades: ['Ceuta'] },
  {
    provincia: 'Ciudad Real',
    ciudades: [
      'Ciudad Real',
      'Puertollano',
      'Tomelloso',
      'Alcázar de San Juan',
      'Valdepeñas',
      'Manzanares',
      'La Solana',
      'Daimiel',
      'Miguelturra',
      'Campo de Criptana',
      'Socuéllamos',
      'Bolaños de Calatrava',
      'Villanueva de los Infantes',
    ],
  },
  {
    provincia: 'Córdoba',
    ciudades: [
      'Córdoba',
      'Lucena',
      'Puente Genil',
      'Montilla',
      'Priego de Córdoba',
      'Cabra',
      'Baena',
      'Palma del Río',
      'Pozoblanco',
      'Peñarroya-Pueblonuevo',
      'Fernán-Núñez',
      'La Carlota',
      'Aguilar de la Frontera',
      'Alcaracejos',
      'Villanueva de Córdoba',
    ],
  },
  {
    provincia: 'Cuenca',
    ciudades: [
      'Cuenca',
      'Tarancón',
      'Quintanar del Rey',
      'Motilla del Palancar',
      'San Clemente',
    ],
  },
  {
    provincia: 'Gipuzkoa',
    ciudades: [
      'San Sebastián',
      'Irun',
      'Errenteria',
      'Eibar',
      'Zarautz',
      'Arrasate',
      'Hernani',
      'Tolosa',
      'Lasarte-Oria',
      'Andoain',
      'Bergara',
      'Azpeitia',
      'Beasain',
      'Oñati',
      'Pasaia',
    ],
  },
  {
    provincia: 'Girona',
    ciudades: [
      'Girona',
      'Figueres',
      'Blanes',
      'Salt',
      'Lloret de Mar',
      'Olot',
      'Palafrugell',
      'Sant Feliu de Guíxols',
      'Banyoles',
      'Ripoll',
      'Roses',
      'Palamós',
      "La Bisbal d'Empordà",
      'Torroella de Montgrí',
      'Aiguaviva',
      'Cassà de la Selva',
    ],
  },
  {
    provincia: 'Granada',
    ciudades: [
      'Granada',
      'Motril',
      'Almuñécar',
      'Baza',
      'Armilla',
      'Maracena',
      'Loja',
      'Guadix',
      'Las Gabias',
      'Albolote',
      'Atarfe',
      'Santa Fe',
      'Huétor Vega',
      'Ogíjares',
      'La Zubia',
      'Peligros',
    ],
  },
  {
    provincia: 'Guadalajara',
    ciudades: [
      'Guadalajara',
      'Azuqueca de Henares',
      'Alovera',
      'Cabanillas del Campo',
      'El Casar',
      'Marchamalo',
      'Sigüenza',
    ],
  },
  {
    provincia: 'Huelva',
    ciudades: [
      'Huelva',
      'Lepe',
      'Almonte',
      'Moguer',
      'Isla Cristina',
      'Ayamonte',
      'Bollullos Par del Condado',
      'Cartaya',
      'Punta Umbría',
      'Aljaraque',
      'Valverde del Camino',
      'Palos de la Frontera',
    ],
  },
  {
    provincia: 'Huesca',
    ciudades: [
      'Huesca',
      'Monzón',
      'Barbastro',
      'Fraga',
      'Jaca',
      'Sabiñánigo',
      'Binéfar',
    ],
  },
  {
    provincia: 'Jaén',
    ciudades: [
      'Jaén',
      'Linares',
      'Andújar',
      'Úbeda',
      'Martos',
      'Alcalá la Real',
      'Bailén',
      'Torredonjimeno',
      'Torreperogil',
      'La Carolina',
      'Villacarrillo',
      'Mancha Real',
      'Jódar',
    ],
  },
  {
    provincia: 'La Rioja',
    ciudades: [
      'Logroño',
      'Calahorra',
      'Arnedo',
      'Haro',
      'Lardero',
      'Nájera',
      'Alfaro',
      'Villamediana de Iregua',
    ],
  },
  {
    provincia: 'Las Palmas',
    ciudades: [
      'Las Palmas de Gran Canaria',
      'Telde',
      'Santa Lucía de Tirajena',
      'Arrecife',
      'Puerto del Rosario',
      'San Bartolomé de Tirajena',
      'Ingenio',
      'Agüimes',
      'Gáldar',
      'Arucas',
      'Mogán',
      'La Oliva',
      'Teguise',
      'Tías',
      'Santa Brígida',
      'Vecindario',
    ],
  },
  {
    provincia: 'León',
    ciudades: [
      'León',
      'Ponferrada',
      'San Andrés del Rabanedo',
      'Villaquilambre',
      'Astorga',
      'La Bañeza',
      'Bembibre',
      'Villablino',
      'Valencia de Don Juan',
    ],
  },
  {
    provincia: 'Lleida',
    ciudades: [
      'Lleida',
      'Balaguer',
      'Tàrrega',
      'Mollerussa',
      'Cervera',
      "La Seu d'Urgell",
      'Les Borges Blanques',
      'Alcarràs',
    ],
  },
  {
    provincia: 'Lugo',
    ciudades: [
      'Lugo',
      'Monforte de Lemos',
      'Viveiro',
      'Vilalba',
      'Sarria',
      'Foz',
      'Ribadeo',
      'Chantada',
      'Burela',
    ],
  },
  {
    provincia: 'Madrid',
    ciudades: [
      'Madrid',
      'Móstoles',
      'Alcalá de Henares',
      'Fuenlabrada',
      'Leganés',
      'Getafe',
      'Alcorcón',
      'Torrejón de Ardoz',
      'Parla',
      'Alcobendas',
      'Las Rozas de Madrid',
      'San Sebastián de los Reyes',
      'Pozuelo de Alarcón',
      'Rivas-Vaciamadrid',
      'Coslada',
      'Valdemoro',
      'Majadahonda',
      'Collado Villalba',
      'Aranjuez',
      'Arganda del Rey',
      'Boadilla del Monte',
      'Pinto',
      'Colmenar Viejo',
      'Tres Cantos',
      'San Fernando de Henares',
      'Galapagar',
      'Villaviciosa de Odón',
      'Mejorada del Campo',
      'Navalcarnero',
      'Ciempozuelos',
      'Torrelodones',
      'Villanueva de la Cañada',
      'Algete',
      'Arroyomolinos',
      'Humanes de Madrid',
      'San Martín de la Vega',
      'Paracuellos de Jarama',
      'Griñón',
    ],
  },
  {
    provincia: 'Málaga',
    ciudades: [
      'Málaga',
      'Marbella',
      'Vélez-Málaga',
      'Mijas',
      'Fuengirola',
      'Torremolinos',
      'Estepona',
      'Benalmádena',
      'Antequera',
      'Rincón de la Victoria',
      'Alhaurín de la Torre',
      'Alhaurín el Grande',
      'Ronda',
      'Cártama',
      'Coín',
      'Nerja',
      'Torrox',
      'Manilva',
      'Álora',
    ],
  },
  { provincia: 'Melilla', ciudades: ['Melilla'] },
  {
    provincia: 'Murcia',
    ciudades: [
      'Murcia',
      'Cartagena',
      'Lorca',
      'Molina de Segura',
      'Alcantarilla',
      'Águilas',
      'Yecla',
      'Cieza',
      'Totana',
      'San Javier',
      'Mazarrón',
      'Jumilla',
      'Caravaca de la Cruz',
      'Torre-Pacheco',
      'Las Torres de Cotillas',
      'San Pedro del Pinatar',
      'Alhama de Murcia',
      'Archena',
      'Fuente Álamo',
      'Bullas',
      'Cehegín',
      'Mula',
    ],
  },
  {
    provincia: 'Navarra',
    ciudades: [
      'Pamplona',
      'Tudela',
      'Barañáin',
      'Burlada',
      'Zizur Mayor',
      'Estella',
      'Tafalla',
      'Villava',
      'Ansoáin',
      'Berriozar',
      'Sangüesa',
      'Corella',
      'Alsasua',
    ],
  },
  {
    provincia: 'Ourense',
    ciudades: [
      'Ourense',
      'O Barco de Valdeorras',
      'Verín',
      'O Carballiño',
      'Xinzo de Limia',
      'Allariz',
      'A Rúa',
    ],
  },
  {
    provincia: 'Palencia',
    ciudades: [
      'Palencia',
      'Aguilar de Campoo',
      'Guardo',
      'Venta de Baños',
      'Villamuriel de Cerrato',
    ],
  },
  {
    provincia: 'Pontevedra',
    ciudades: [
      'Pontevedra',
      'Vigo',
      'Vilagarcía de Arousa',
      'Redondela',
      'Marín',
      'Cangas',
      'A Estrada',
      'Lalín',
      'Ponteareas',
      'O Porriño',
      'Moaña',
      'Sanxenxo',
      'Tui',
      'Poio',
      'Cambados',
      'Nigrán',
      'Bueu',
      'Gondomar',
    ],
  },
  {
    provincia: 'Salamanca',
    ciudades: [
      'Salamanca',
      'Béjar',
      'Ciudad Rodrigo',
      'Santa Marta de Tormes',
      'Villamayor',
      'Guijuelo',
      'Peñaranda de Bracamonte',
    ],
  },
  {
    provincia: 'Santa Cruz de Tenerife',
    ciudades: [
      'Santa Cruz de Tenerife',
      'San Cristóbal de La Laguna',
      'Arona',
      'Granadilla de Abona',
      'Adeje',
      'La Orotava',
      'Los Realejos',
      'Puerto de la Cruz',
      'Candelaria',
      'Icod de los Vinos',
      'Tacoronte',
      'Santa Úrsula',
      'Guía de Isora',
      'El Rosario',
      'Los Llanos de Aridane',
      'Santa Cruz de la Palma',
    ],
  },
  {
    provincia: 'Segovia',
    ciudades: [
      'Segovia',
      'Cuéllar',
      'El Espinar',
      'San Ildefonso',
      'Cantalejo',
    ],
  },
  {
    provincia: 'Sevilla',
    ciudades: [
      'Sevilla',
      'Dos Hermanas',
      'Alcalá de Guadaíra',
      'Utrera',
      'Mairena del Aljarafe',
      'Écija',
      'La Rinconada',
      'Coria del Río',
      'Los Palacios y Villafranca',
      'Camas',
      'Morón de la Frontera',
      'Lebrija',
      'Carmona',
      'Tomares',
      'San Juan de Aznalfarache',
      'Bormujos',
      'Mairena del Alcor',
      'Marchena',
      'Osuna',
      'Estepa',
      'Gines',
      'Sanlúcar la Mayor',
      'Cantillana',
      'Arahal',
    ],
  },
  {
    provincia: 'Soria',
    ciudades: ['Soria', 'Almazán', 'Ólvega', 'San Esteban de Gormaz'],
  },
  {
    provincia: 'Tarragona',
    ciudades: [
      'Tarragona',
      'Reus',
      'Tortosa',
      'Cambrils',
      'El Vendrell',
      'Valls',
      'Salou',
      'Amposta',
      'Vila-seca',
      'Calafell',
      'Sant Carles de la Ràpita',
      'Deltebre',
      'Torredembarra',
      "Móra d'Ebre",
    ],
  },
  {
    provincia: 'Teruel',
    ciudades: [
      'Teruel',
      'Alcañiz',
      'Andorra',
      'Utrillas',
      'Calanda',
      'Alcorisa',
    ],
  },
  {
    provincia: 'Toledo',
    ciudades: [
      'Toledo',
      'Talavera de la Reina',
      'Illescas',
      'Seseña',
      'Torrijos',
      'Sonseca',
      'Consuegra',
      'Madridejos',
      'Quintanar de la Orden',
      'Ocaña',
      'Villacañas',
      'Yuncos',
      'Mora',
      'Bargas',
    ],
  },
  {
    provincia: 'Valencia',
    ciudades: [
      'Valencia',
      'Torrent',
      'Gandia',
      'Paterna',
      'Sagunto',
      'Alzira',
      'Mislata',
      'Burjassot',
      'Ontinyent',
      'Xàtiva',
      'Cullera',
      'Manises',
      'Aldaia',
      'Alaquàs',
      'Quart de Poblet',
      'Catarroja',
      'Sueca',
      'Paiporta',
      'Silla',
      'Oliva',
      'Requena',
      'Algemesí',
      'Carcaixent',
      'Bétera',
      'Albuixech',
      'Alcàsser',
      'Picassent',
      'Llíria',
      'Godella',
      'Tavernes de la Valldigna',
      'Alboraya',
      'La Pobla de Vallbona',
      'Massamagrell',
      'Chiva',
      'Bunyol',
    ],
  },
  {
    provincia: 'Valladolid',
    ciudades: [
      'Valladolid',
      'Medina del Campo',
      'Laguna de Duero',
      'Arroyo de la Encomienda',
      'Tordesillas',
      'Íscar',
      'Tudela de Duero',
      'Cigales',
    ],
  },
  {
    provincia: 'Zamora',
    ciudades: ['Zamora', 'Benavente', 'Toro', 'Morales del Vino'],
  },
  {
    provincia: 'Zaragoza',
    ciudades: [
      'Zaragoza',
      'Calatayud',
      'Utebo',
      'Ejea de los Caballeros',
      'Tarazona',
      'Caspe',
      'La Almunia de Doña Godina',
      'Zuera',
      'Cuarte de Huerva',
      'Fuentes de Ebro',
    ],
  },
];
