export const UBICACIONES_POR_PROVINCIA = [
  {
    provincia: 'A Coruña',
    ciudades: [
      'A Coruña',
      'Santiago de Compostela',
      'Ferrol',
      'Narón',
      'Oleiros',
      'Arteixo',
      'Culleredo',
    ],
  },
  { provincia: 'Álava', ciudades: ['Vitoria-Gasteiz'] },
  {
    provincia: 'Albacete',
    ciudades: ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa'],
  },
  {
    provincia: 'Alicante',
    ciudades: [
      'Alicante',
      'Elche',
      'Torrevieja',
      'Orihuela',
      'Benidorm',
      'Alcoy',
      'Elda',
      'San Vicente del Raspeig',
      'Dénia',
      'Villena',
      'Petrer',
      'La Vila Joiosa',
      'Santa Pola',
    ],
  },
  {
    provincia: 'Almería',
    ciudades: [
      'Almería',
      'Roquetas de Mar',
      'El Ejido',
      'Níjar',
      'Adra',
      'Vícar',
      'Huércal de Almería',
    ],
  },
  {
    provincia: 'Asturias',
    ciudades: ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres'],
  },
  { provincia: 'Ávila', ciudades: ['Ávila'] },
  {
    provincia: 'Badajoz',
    ciudades: [
      'Badajoz',
      'Mérida',
      'Don Benito',
      'Almendralejo',
      'Villanueva de la Serena',
    ],
  },
  {
    provincia: 'Baleares',
    ciudades: [
      'Palma',
      'Calvià',
      'Manacor',
      'Ibiza',
      'Santa Eulària des Riu',
      'Llucmajor',
      'Marratxí',
    ],
  },
  {
    provincia: 'Barcelona',
    ciudades: [
      'Barcelona',
      "L'Hospitalet de Llobregat",
      'Badalona',
      'Terrassa',
      'Sabadell',
      'Mataró',
      'Santa Coloma de Gramenet',
      'Cornellà de Llobregat',
      'Sant Cugat del Vallès',
      'Manresa',
      'Rubí',
      'Vilanova i la Geltrú',
      'Viladecans',
      'El Prat de Llobregat',
      'Castelldefels',
      'Granollers',
      'Cerdanyola del Vallès',
      'Mollet del Vallès',
      'Sant Boi de Llobregat',
      'Esplugues de Llobregat',
      'Gavà',
      'Igualada',
      'Vic',
    ],
  },
  {
    provincia: 'Bizkaia',
    ciudades: [
      'Bilbao',
      'Barakaldo',
      'Getxo',
      'Portugalete',
      'Santurtzi',
      'Basauri',
      'Leioa',
    ],
  },
  {
    provincia: 'Burgos',
    ciudades: ['Burgos', 'Miranda de Ebro', 'Aranda de Duero'],
  },
  { provincia: 'Cáceres', ciudades: ['Cáceres', 'Plasencia'] },
  {
    provincia: 'Cádiz',
    ciudades: [
      'Cádiz',
      'Jerez de la Frontera',
      'Algeciras',
      'San Fernando',
      'El Puerto de Santa María',
      'Chiclana de la Frontera',
      'La Línea de la Concepción',
      'Sanlúcar de Barrameda',
      'Puerto Real',
      'Rota',
      'Arcos de la Frontera',
    ],
  },
  {
    provincia: 'Cantabria',
    ciudades: ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo'],
  },
  {
    provincia: 'Castellón',
    ciudades: ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Vinaròs'],
  },
  { provincia: 'Ceuta', ciudades: ['Ceuta'] },
  {
    provincia: 'Ciudad Real',
    ciudades: [
      'Ciudad Real',
      'Puertollano',
      'Tomelloso',
      'Alcázar de San Juan',
      'Valdepeñas',
    ],
  },
  {
    provincia: 'Córdoba',
    ciudades: ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla'],
  },
  { provincia: 'Cuenca', ciudades: ['Cuenca'] },
  { provincia: 'Gipuzkoa', ciudades: ['San Sebastián', 'Irun', 'Errenteria'] },
  {
    provincia: 'Girona',
    ciudades: ['Girona', 'Figueres', 'Blanes', 'Salt', 'Lloret de Mar'],
  },
  {
    provincia: 'Granada',
    ciudades: ['Granada', 'Motril', 'Almuñécar', 'Baza', 'Armilla', 'Maracena'],
  },
  {
    provincia: 'Guadalajara',
    ciudades: ['Guadalajara', 'Azuqueca de Henares'],
  },
  { provincia: 'Huelva', ciudades: ['Huelva', 'Lepe', 'Almonte', 'Moguer'] },
  { provincia: 'Huesca', ciudades: ['Huesca', 'Monzón'] },
  {
    provincia: 'Jaén',
    ciudades: ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos'],
  },
  { provincia: 'La Rioja', ciudades: ['Logroño', 'Calahorra'] },
  {
    provincia: 'Las Palmas',
    ciudades: [
      'Las Palmas de Gran Canaria',
      'Telde',
      'Santa Lucía de Tirajena',
      'Arrecife',
      'Puerto del Rosario',
    ],
  },
  {
    provincia: 'León',
    ciudades: ['León', 'Ponferrada', 'San Andrés del Rabanedo'],
  },
  { provincia: 'Lleida', ciudades: ['Lleida'] },
  { provincia: 'Lugo', ciudades: ['Lugo'] },
  {
    provincia: 'Madrid',
    ciudades: [
      'Madrid',
      'Móstoles',
      'Alcalá de Henares',
      'Fuenlabrada',
      'Leganés',
      'Getafe',
      'Alcorcón',
      'Torrejón de Ardoz',
      'Parla',
      'Alcobendas',
      'Las Rozas de Madrid',
      'San Sebastián de los Reyes',
      'Pozuelo de Alarcón',
      'Rivas-Vaciamadrid',
      'Coslada',
      'Valdemoro',
      'Majadahonda',
      'Collado Villalba',
      'Aranjuez',
      'Arganda del Rey',
      'Boadilla del Monte',
      'Pinto',
      'Colmenar Viejo',
      'Tres Cantos',
      'San Fernando de Henares',
    ],
  },
  {
    provincia: 'Málaga',
    ciudades: [
      'Málaga',
      'Marbella',
      'Vélez-Málaga',
      'Mijas',
      'Fuengirola',
      'Torremolinos',
      'Estepona',
      'Benalmádena',
      'Antequera',
      'Rincón de la Victoria',
      'Alhaurín de la Torre',
    ],
  },
  { provincia: 'Melilla', ciudades: ['Melilla'] },
  {
    provincia: 'Murcia',
    ciudades: [
      'Murcia',
      'Cartagena',
      'Lorca',
      'Molina de Segura',
      'Alcantarilla',
      'Águilas',
      'Yecla',
      'Cieza',
      'Totana',
      'San Javier',
      'Mazarrón',
    ],
  },
  { provincia: 'Navarra', ciudades: ['Pamplona', 'Tudela', 'Barañáin'] },
  { provincia: 'Ourense', ciudades: ['Ourense'] },
  { provincia: 'Palencia', ciudades: ['Palencia'] },
  {
    provincia: 'Pontevedra',
    ciudades: [
      'Pontevedra',
      'Vigo',
      'Vilagarcía de Arousa',
      'Redondela',
      'Marín',
    ],
  },
  { provincia: 'Salamanca', ciudades: ['Salamanca'] },
  {
    provincia: 'Santa Cruz de Tenerife',
    ciudades: [
      'Santa Cruz de Tenerife',
      'San Cristóbal de La Laguna',
      'Arona',
      'Granadilla de Abona',
      'Adeje',
    ],
  },
  { provincia: 'Segovia', ciudades: ['Segovia'] },
  {
    provincia: 'Sevilla',
    ciudades: [
      'Sevilla',
      'Dos Hermanas',
      'Alcalá de Guadaíra',
      'Utrera',
      'Mairena del Aljarafe',
      'Écija',
      'La Rinconada',
      'Coria del Río',
    ],
  },
  { provincia: 'Soria', ciudades: ['Soria'] },
  {
    provincia: 'Tarragona',
    ciudades: [
      'Tarragona',
      'Reus',
      'Tortosa',
      'Cambrils',
      'El Vendrell',
      'Valls',
    ],
  },
  { provincia: 'Teruel', ciudades: ['Teruel'] },
  { provincia: 'Toledo', ciudades: ['Toledo', 'Talavera de la Reina'] },
  {
    provincia: 'Valencia',
    ciudades: [
      'Valencia',
      'Gandia',
      'Torrent',
      'Sagunto',
      'Paterna',
      'Alzira',
      'Mislata',
      'Burjassot',
      'Xàtiva',
      'Ontinyent',
      'Cullera',
    ],
  },
  {
    provincia: 'Valladolid',
    ciudades: ['Valladolid', 'Medina del Campo', 'Laguna de Duero'],
  },
  { provincia: 'Zamora', ciudades: ['Zamora'] },
  { provincia: 'Zaragoza', ciudades: ['Zaragoza', 'Calatayud', 'Utebo'] },
];

export default UBICACIONES_POR_PROVINCIA;
