name: Deploy Nexus Agent

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy a la VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy en VM GCP
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/nexus-app &&
            git config pull.rebase false &&
            git pull origin develop &&
            cd backend &&
            source ~/nexus-app/venv/bin/activate &&
            pip install -r requirements.txt --quiet &&
            sudo systemctl restart aratalent &&
            cd ~/nexus-app/frontend &&
            npm install --quiet &&
            npm run build &&
            echo '✅ Deploy completado'